### ISSUE TITLE
NPM elements missing from author page

### ISSUE THREAD

**Issue by LostInBrittany** [webcomponents/webcomponents.org#1177]
Hi! 

I have recently begun to migrate my [granite-elements](https://www.webcomponents.org/collection/LostInBrittany/granite-elements) collection to npm based Polymer 3 elements, and I've found a weird bug.

I have migrated 3 elements by now: 
- [granite-alarmlight](https://www.webcomponents.org/element/@granite-elements/granite-alarmlight)
- [granite-c3](https://www.webcomponents.org/element/@granite-elements/granite-c3)
- [granite-js-dependencies-grabber](https://www.webcomponents.org/element/@granite-elements/granite-js-dependencies-grabber)

In the 3 elements page I appear as the element author:
![image](https://user-images.githubusercontent.com/726476/40920066-c45a1988-680b-11e8-863e-e88adfb86d2c.png)

But when I go to my [author page](https://www.webcomponents.org/author/LostInBrittany) the three npm based elements are missing. I posted the bug on gitter and @samuelli suggested me to report it here...

**Comment by muan** [comment]
None of our packages show up in [our collection](https://github.com/github/github-elements): https://www.webcomponents.org/collection/github/github-elements
or under @github author:
https://www.webcomponents.org/author/github

I guess it's due to them not having `bower.json` (even thought they can be installed via bower)? Is there any workarounds?

**Comment by notwaldorf** [comment]
cc @samuelli

**Comment by samuelli** [comment]
This is fixed now! Sorry for the wait @LostInBrittany, it was on lower priority than getting NPM based demos up to scratch.
