### ISSUE TITLE
Element demos missing webcomponents polyfills

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/webcomponents.org#786]
Some embedded element demos don't load the polyfills, and so don't work in Safari. E.g. currently: https://www.webcomponents.org/element/vogelrh/ken-burns-image

Perhaps there's a way the catalog could see if they're a dependency and load them in?

**Comment by samuelli** [comment]
Hmm, that's interesting. I'm not sure if we should be handling that since there are so many combinations. @dstockwell: thoughts?

**Comment by dstockwell** [comment]
I think it's going to be hard/impossible to determine whether we need to inject a polyfill (and which one). Some ideas:

* The inline demo creator already prefills the source with a polyfill, we should make sure we do this in any templates that include inline demos.
* We could add a button so that users can file issues on the author's repo when this happens.
* Maybe a button to launch the demo on a browsershots site?

**Comment by tjsavage** [comment]
Perhaps we could start with just adding an extra comment in the inline demo creator, and a note on the /publish page under "add an inline demo" reminding people to include all their necessary dependencies, including polyfills?
