### ISSUE TITLE
Most pages are missing a title

### ISSUE THREAD

**Issue by matthewp** [webcomponents/webcomponents.org#825]
Except for element listings, most other pages such as community and publish have the same title, `webcomponents.org`.

I'm not too familiar with the "polymer way", would you emit an event from, for example, `<catalog-publish>` called `page-title` or something, and have a parent element set the title that way?

**Comment by matthewp** [comment]
Willing to submit a PR on this if given some advice on the best way to do it.

**Comment by samuelli** [comment]
Event seems fine to me, maybe called `document-title` then the main `<catalog-app>` can listen to that event and append webcomponents.org if it likes. Currently some pages just set it directly - I believe that's what `<catalog-element>` does, but events are probably more 'polymer way'.

PR would be great! Maybe just start with event and 1-2 places of setting the title, then add the rest in a separate PR. How does that sound?

**Comment by matthewp** [comment]
Sounds like a good way to go to me. Any particular pattern you like for titles, for example do you prefer keeping `webcomponents.org` as part of it like:

```
Publish | webcomponents.org
```

Or just

```
Publish element
```

**Comment by samuelli** [comment]
Probably the first, seems to be convention:

Wikipedia has ` - Wikipedia`
Twitter ` | Twitter`
Facebook none
Google ` - Google Search`

**Comment by matthewp** [comment]
Hey @samuelli, it turns out there's not a good place to trigger the event from within the page, because the pages are not inserted each time so you can't used `attached`. They are set to `display: none;` when not visible.

Couple of ideas here, one is to add a page-title attribute to the element, some of the elements already have this. Would be like:

```html
<catalog-community name="community" path="[[_filter('/community', subroute.prefix, subroute.path)]]" page-title="Community"></catalog-community>
```

And then inside of `_pageReady` check for `this.$.pages.selectedItem.getAttribute('page-title')` and use that to set the document.title.

That would be the easiest solution. Another, more robust, solution would be if catalog-app supported a lifecycle callback for when the page become visible. Maybe called `visible`, and if the page implements this callback, catalog-app would call this function after it becomes visible. From there the page could trigger the document-title event.

The benefit of the second idea is that if there was anything else the page wanted to do when it became visible, the callback would allow it to do whatever it needed.

Let me know which you prefer (or if you have another idea).

**Comment by samuelli** [comment]
Hmm, `page-title` is currently used for the top level `<h1>` tag on static pages.

`<iron-pages>` already supports a selected attribute which we use in a lot of places as `visible`. See [this example](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-element.html#L699).

So I think I still prefer the event solution since it allows a) propagation so it doesn't need to be in a top level page element and b) can be done at any time eg. [in this case](https://github.com/webcomponents/webcomponents.org/blob/master/client/src/catalog-element.html#L801) we change the title based on what element is being viewed. We should be able to then add `visible` observers on other pages.

That might've been a mouthful, does that make sense?

Thanks for looking into this!

**Comment by matthewp** [comment]
Yeah, page-title felt wrong for that reason, reusing something for a different purpose.

I think that makes sense, I'll try and let you know. Thanks.

**Comment by samuelli** [comment]
Hey @matthewp: any other pages that are missing document titles still? I think you got them all.

**Comment by matthewp** [comment]
I think I got them all. At least intended to!
