### ISSUE TITLE
Issues adding a component

### ISSUE THREAD

**Issue by PaulKinlan** [webcomponents/webcomponents.org#827]
I recently added https://www.webcomponents.org/element/PaulKinlan/air-horner to the directory and it got stuck.

First time around it said there wasn't a tagged version, yet I believe there was. I did note that my README.md was not correct (which I fixed).
Second time I tried to add the component again, but all I saw on the screen was a progress bar cycling.

I did make a number of commits thinking that it was something to do with me, but everytime I tried to add it to the directory I just got a blank page with the progress bar.

I pinged taylor about it, and he said he could see the element in the directory.

**Comment by samuelli** [comment]
Thanks for the report @PaulKinlan. I'll dig into the logs a bit and test out more of the publishing flow.

I can see [the element](https://www.webcomponents.org/element/PaulKinlan/air-horner) fine.

a) tagged version - interesting, I'll see if the logs reveal anything.
b) progress bar cycling - I think our SW has been causing us some pain for caching error'd out cases probably because of the error in a). I'll look more into this.

**Comment by samuelli** [comment]
@PaulKinlan: as far as I can tell, there weren't any tagged versions that we were seeing at the time of the initial publishing. An update cycle 10 minutes later found a tagged version and processed it then.

The 'no tagged version' error should also probably clarify that this means it couldn't find any _valid_ (semver) version.

#832 fixes the forever loading bug you were seeing which was caused by internal navigations to the same cached page.

**Comment by ankitsorathiya** [comment]
I have recently created [https://github.com/ankitsorathiya/iron-multiple-ajax-behavior](url). When I try to publish it it says unable to process element couldn't find any tagged version. I waited for half and hour to publish after creating tag but it did not work out. can someone help what am I missing here?

**Comment by samuelli** [comment]
Hi @ankitsorathiya,

Only valid semver tags are accepted. Try something like `v1.0.0`.

Also ref #864, where we can try explain this better.
