### ISSUE TITLE
new site layout

### ISSUE THREAD

**Issue by JoernT** [webcomponents/webcomponents.org#852]
[Origin page](https://www.webcomponents.org/collection/Polymer/elements)

i'm missing the bower install options for quick copying.

Futher no link to the github repo any more?

Though i appreciate to have all web components in one site now (not just the polymer ones i've been using most) the overview is not much harder. Things are sub-categorized which does not make finding things easier.

Overall nice job but overview is still the biggest issue.

Thanks for the hard work

**Comment by samuelli** [comment]
Hi,

The bower install and github link are in the sidebar (see screenshot):
![image](https://cloud.githubusercontent.com/assets/787668/22635123/aad1f93a-ec84-11e6-9768-3b372bb9b7d1.png)

Can you be more specific about what the "overview" is?

**Comment by chuihinwai** [comment]
That's very subtle. I had trouble finding that. Installing would be the most common action and it should be presented prominently

**Comment by kovilyn** [comment]
hi... since things haven't changed, will make a small positive constructive comment :)

I think the Polymer Elements catalogue was a much better intuitive design, to find and use elements. Currently WebComponents.org it is rather difficult to see things. 
One option to improve would be to adopt the previous Polymer site layout and flow, and include other elements to them.

(seen the dynamic where things work very well in separate teams, but when exposed to different environment and dynamic, then the same things don't work as well. Unconsciously, to the new collective things go with the new environment (eg hype of (usually) non_-tech/_-analytical new interrelations, org influence/politics, perceived status etc) .. and not for the overall purposes of the original well intentioned tech/analytic groups.
seems wise to reroute the path to easily access easy-to-use components :) 

thanks for the great work! 👍
