### ISSUE TITLE
Demo support without Hydrolysis / Analyzer [Feature Request]

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#899]
It seems like right now in order to publish a dedicated demo page with a web component, you have to implement `iron-component-page` and use the inline documentation with the @demo tag. It would be nice to be able to publish a demo page without the dependency on the Polymer hydrolysis/analyzer.

Maybe this could be a custom bower tag or a meta header in the index.html?

**Comment by samuelli** [comment]
Sounds like a pretty good idea.

@dstockwell wdyt of this implementation:
 * Expose as bower.json array like `demos: ['demo/demo.html']`
 * Expose in `api/metadata`
 * Add to sidebar

Probably some deduping needed with any demos from hydrolysis/analyzer, but that should be it, right?

**Comment by chrismbeckett** [comment]
Wow, that was fast. You are awesome Samuel - Thank you :)

**Comment by seaneking** [comment]
Big 👍 Would love to see webcomponents.org move to a more general interface, rather than a frontend for `iron-component-page` / hydrolisis

**Comment by samuelli** [comment]
This has now landed in production with this [repo using it](https://www.webcomponents.org/element/samuelli/progress-bar). This is the [PR that was used to generate this](https://github.com/samuelli/progress-bar/commit/51585c9433084fde5f770d015c71006617470748).

@seaneking: we could extend this to other pages, like docs. Simply a series of markdown pages.
```json
pages: {
   "<my-element> doc": "api.md",
   "Contributing": "contributing.md",
   "my other doc": "otherdoc.md"
}
```

Thoughts?

**Comment by chrismbeckett** [comment]
I didn't want to push my luck by asking for too much, but the ability to publish additional markdown pages manually would be fantastic as well :)

**Comment by seaneking** [comment]
@samuelli could be good - something I think would definitely be useful in that case is a way generate the current API pages (which are lovely) from markdown or similar rather than hydrolisis - eg: we ship minified components so comments are stripped.

My only concern with arbitrary md pages would be feature bloat (straying into wiki territory). But in reality it's not really adding bloat for the user (already have sidebar with readme/demo/etc, which is where I imagine these pages would appear), and gives more power for component authors if they want it. So I'd lean towards :+1:

**Comment by chrismbeckett** [comment]
Yeah, the auto-generated API pages are lovely, and I know that as they replace upgrade that system with the new analyzer, cool stuff will come from it. I guess for people that want to generate web components not built with Polymer, or want to generate documentation another way, this is an available choice.

**Comment by samuelli** [comment]
Tracking and continuing the convo in #904
