### ISSUE TITLE
Support arbitrary markdown docs specified in bower.json

### ISSUE THREAD

**Issue by samuelli** [webcomponents/webcomponents.org#904]
Idea from #899

**Comment by samuelli** [comment]
@seaneking: what would be the case for generating? The UI is pretty minimal and can be replicated in markdown. A nice markdown template might make it easier and more consistent. Generating is powerful because it allows for documentation in source & for the generation to do some of the work by looking at the source and generating useful info.

The bloat isn't really on us tbh since we're backing heavily onto GitHub. You would essentially just be naming & linking a set of files in your repo. No other magic so in terms of implementation its pretty simple. Would probably also solve cases where you want more extended documentation in specific use cases.

@chrismbeckett: ask away! If you ever feel like you're asking too much, you're always welcome to send PRs ;)

**Comment by seaneking** [comment]
>  A nice markdown template might make it easier and more consistent. 

That's what I meant - not getting rid of the generated docs, just having a way of creating consistent API refs in components that don't support hydrolysis for whatever reason. Just classes/el wrappers/something on md tables to style them the same as generated API tables would do the trick IMO

> The bloat isn't really on us tbh since we're backing heavily onto GitHub

Yeah I was talking feature bloat (just because something is easy doesn't mean it should be built). But as I said, extra cognitive weight for users is pretty small since the UI for this is already there, so probably makes sense

**Comment by seaneking** [comment]
Awesome to see a PR for this so quickly! 

Any update on exposing a styling hook of some kind for consistent property/API tables? Would definitely be keen to use this + some kind of element/mixin/class for custom API references. Right now we just chuck a basic table in the README, which is decidedly less nice.

**Comment by samuelli** [comment]
No update yet on a styling hook.

TBH I'm stumped atm on what to do. Looking at migrating to use the new [`iron-doc-viewer`](https://github.com/PolymerElements/iron-doc-viewer/tree/2.0-analyzer) which is what's used on the [new Polymer docs](https://www.polymer-project.org/2.0/docs/api/elements/Polymer.Element).

I think we could probably do better in terms of matching webcomponents.org styling, but my design skills are lacking here.
