### ISSUE TITLE
Demos don't pull in bower devDependencies properly?

### ISSUE THREAD

**Issue by seaneking** [webcomponents/webcomponents.org#933]
Seems webcomponents.org doesn't always pull in Bower `devDependencies` properly, so if you define extra deps only used in your demo as `devDependencies`, then demos don't work. Looks like this is intermittent though.

Eg - the [simpla-img](https://webcomponents.org/element/SimplaElements/simpla-img) element works, but [simpla-link](https://webcomponents.org/element/SimplaElements/simpla-link) doesn't, with 400s thrown for the demo helpers it's using.

**Comment by samuelli** [comment]
Hey Sean,

Pathing is incorrect.
eg. This was a 400:
```
https://user-content-dot-custom-elements.appspot.com/SimplaElements/simpla-link/v0.1.1/simpla-link/iron-demo-helpers/demo-snippet.html```
Should be:
```
https://user-content-dot-custom-elements.appspot.com/SimplaElements/simpla-link/v0.1.1/iron-demo-helpers/demo-snippet.html
```

I let Bede know the same thing, but all deps should be treated as siblings of your repo, so because [your demo](https://github.com/SimplaElements/simpla-link/blob/master/demo/index.html) is inside the `demo` folder, it needs `../../imported/other-element.html`.

Hope that helps.

**Comment by seaneking** [comment]
derp. Thanks @samuelli, my bad.
