### ISSUE TITLE
Latest release, manual docs broken (API pages being generated)

### ISSUE THREAD

**Issue by chrismbeckett** [webcomponents/webcomponents.org#968]
It looks like a recent release has introduced changes to documentation generation. All of my nebula elements docs now seem broken. The manual doc pages are not being displayed, but API docs are being auto-generated.

Example: https://www.webcomponents.org/element/arsnebula/nebula-validate

With the move to the new analyzer, I didn't think documentation pages were going to be generated on the fly anymore? What is the guidance on documenting v2 elements moving forward?

**Comment by samuelli** [comment]
So it looks like in the move to analyzer they got a little broken - this has been fixed now.

Apologies if it wasn't clear what the intention here was. Custom/manual documentation pages were brought in as an additional option for pages that might not be automatically generated. The port to the new analyzer was done precisely because it allows for generation of docs for Polymer 2.0 elements and vanilla class-based elements.

Broadly speaking, we encourage people to use inline documentation since the source is always the 'source of truth' and therefore the best place to be documenting. Custom/manual pages should be used in cases were auto docs won't work, or for more detailed guides and documentation eg. samples of how to solve a particular use cases, interoperability with x etc.

**Comment by chrismbeckett** [comment]
No misunderstanding Sam :) I fully expected that at some point auto-generated docs would be available for v2.

However, it seems that webcomponents.org should be a site where any custom element can be published - not just elements built with Polymer?

Right now it seems that how the analyzer extracts documentation is very dependent on Polymer constructs and naming conventions.

Are you saying that there is no way to opt-in/opt-out of auto-generated API docs?

**Comment by samuelli** [comment]
> However, it seems that webcomponents.org should be a site where any custom element can be published - not just elements built with Polymer?

Yep

> Right now it seems that how the analyzer extracts documentation is very dependent on Polymer constructs and naming conventions.

It does extract Polymer concepts really well simply because it has the structure and details we need.

It also extracts what it can from vanilla custom elements, which shows properties, methods etc, which aren't Polymer specific.

> Are you saying that there is no way to opt-in/opt-out of auto-generated API docs?

There isn't, but it only generates if it was able to process them successfully.

**Comment by chrismbeckett** [comment]
Ok. I seem to have read somewhere that the analyzer is using the eslint/doctrine engine for extracting comments. I did notice it seems to respect the @private, @protected and @public tags (I have started using symbols rather than underscore notation for protected and private members).

I hope that eventually the v2 pages provide a more comprehensive overview of what tags are supported. I also read in the analyzer issues list something about the generated API changed from *Show Private* to *Show Protected*? Is this still a change that is pending? It does seem that the the generated docs pages say *private* when the mean *protected*. This is sort of important in that I want to be able to use the @private and @protected tags to control what members show up on the generated API pages. It would be preferred if @private were not extracted.

I will run a little test to see if it respects the JSDoc @ignore tag. If it does, then this would be one approach to allow people to opt-out and manually document their elements if they want to.

**Comment by samuelli** [comment]
I'm not aware of all the details sorry.

Main repo: https://github.com/polymer/polymer-analyzer

I think you will want to use @protected instead of @private if you want it to be able to show up. AFAIK, @private won't show up one day.

**Comment by chrismbeckett** [comment]
The @ignore JSDoc tag doesn't seem to be supported.

Can you tell me how webcomponents.org *finds* elements to generate the API pages? I don't have an `index.html` using `iron-component-page`? Is it using the `main` property in bower.json?

**Comment by samuelli** [comment]
Yes the main property is used to find elements.

**Comment by chrismbeckett** [comment]
Thanks for all the help and info Sam. Manual docs are working again, so I will close this off.
